Repository HackathonCovid/helpCovidFront, pull requests merged in 2020-04, with the labels that each got.

#4 Feat: Crud missions
  package-lock.json
  src/components/Missions/AddMission.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/FicheMission.js
  src/components/Missions/MesMissions.js
  src/components/Missions/Missions.js
  src/components/Missions/UpdateMission.js
Labels: enhancement

#6 Commentaire
  src/components/Missions/CommentaireMission.js
Labels: enhancement

#7 Modifications multiples
  package-lock.json
  package.json
  src/App.js
  src/GA.js
  src/components/Auth/Register.js
  src/components/Missions/AddMission.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
  src/components/Profil/Profile.js
Labels: bug, enhancement

#8 Feat & fix : ChangePassword - fix : mission - DeleteComment & refactor
  src/App.js
  src/components/Auth/Register.js
  src/components/Missions/AddMission.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
  src/components/Profil/ChangerMdp.js
Labels: bug, enhancement

#9 initalize panel appliant with call api to list them
  src/components/Missions/AdminApplyant.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/FicheMission.js
Labels: enhancement

#10 Modification/fix
  src/App.js
  src/components/Missions/MesMissionsApp.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
  src/components/Profil/ChangerMdp.js
Labels: bug

#11 apply to a mission module : apply and remove application
  src/components/Missions/Missions.js
Labels: enhancement

#15 Fix design2
  public/img.jpg
  src/components/Missions/FicheMission.js
  src/components/Missions/MesMissions.js
  src/components/Missions/MesMissionsApp.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
Labels: bug

#16 Add right access
  src/components/Missions/FicheMission.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
Labels: bug

#17 Photo card
  public/favicon.ico
  src/components/Missions/AddMission.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/MesMissionsApp.js
  src/components/Profil/ChangerMdp.js
Labels: bug, enhancement

#18 fix rapides
  src/components/Missions/MesMissionsApp.js
  src/components/Missions/Missions.js
  src/components/Missions/UpdateMission.js
  yarn.lock
Labels: bug

#20 Add change design
  public/manifest.json
  src/components/Auth/Login.js
  src/components/Auth/Register.js
  src/components/Footer/Footer.js
  src/components/Missions/FicheMission.js
  src/components/Navbar/Navbar.js
Labels: bug

#21 Fixnavbaresponsive
  src/components/Navbar/Navbar.js
Labels: bug

#23 Correction des bugs d affichage
  src/components/Missions/AdminApplyant.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/FicheMission.js
  src/components/Missions/MesMissions.js
  src/components/Missions/MesMissionsApp.js
  src/components/Missions/Missions.js
Labels: bug

#25 Fix design and warnings
  src/components/Auth/Register.js
  src/components/Missions/AddMission.js
  src/components/Missions/AdminApplyant.js
  src/components/Missions/CommentaireMission.js
  src/components/Missions/FicheMission.js
  src/components/Missions/MesMissions.js
  src/components/Missions/MesMissionsApp.js
  src/components/Missions/Missions.js
  src/components/Navbar/Navbar.js
  src/components/Profil/Profile.js
Labels: bug
